### PR TITLE
Strip off the keychain team ID from the keychain sharing group before…

### LINKED ISSUE #810: Keychain "add" operation fails from brokered auth
Users are unable to stay logged in because the brokered auth flow fails to save tokens to keychain. Non-broker flow is fine.

branch: `release/2.2.7`

App logs:

> ADAL 2.2.7 iOS 10.0.2 [2016-10-14 20:01:12] Error raised: (Domain: "ADKeychainErrorDomain" Code: -34018 ProtocolCode: "(null)" Details: "Keychain failed during "add" operation" (errorCode=-34018, additionalInfo=(null), userInfo={
    error = "Error with code: -34018 Domain: ADKeychainErrorDomain ProtocolCode:(null) Details:Keychain failed during \"add\" operation. Inner error details: Error Domain=ADKeychainErrorDomain Code=-34018 \"(null)\"";
})

Device console: 

> add Error Domain=NSOSStatusErrorDomain Code=-34018 "explicit accessGroup TEAMID.TEAMID.com.microsoft.adalcache not in client access

### PR DESCRIPTION
**Pull request by RPangrle**
… saving it in the resume dictionary

Fixes #810

### CODE REVIEW

**Comment by RPangrle** [comment]
@joeydong

File: ADAL/src/request/ADAuthenticationRequest+Broker.m [hunk 1]
```diff
@@ -306,14 +307,25 @@ - (void)callBroker:(ADAuthenticationCallback)completionBlock
     id<ADTokenCacheDataSource> dataSource = [_tokenCache dataSource];
     if (dataSource && [dataSource isKindOfClass:[ADKeychainTokenCache class]])
     {
+        NSString* keychainGroup = [(ADKeychainTokenCache*)dataSource sharedGroup];
+        NSString* teamId = [ADKeychainUtil keychainTeamId:&error];
```
Comment (joeydong) [inline ADAL/src/request/ADAuthenticationRequest+Broker.m]: is it possible for `[ADKeychainUtil keychainTeamId:&error];` to return something like an empty string and also an error?

Comment (joeydong) [inline ADAL/src/request/ADAuthenticationRequest+Broker.m]: I traced through the code a little bit and I guess we're fine because you check the result length in `ADKeychainUtil.retrieveTeamIDFromKeychain`.

This leads me to another question: The query you use in `ADKeychainUtil.retrieveTeamIDFromKeychain` searches for a keychain item with `teamIDHint` but `ADKeychainTokenCache` inserts a keychain item with no label. Are these two separate systems?

**Comment by joeydong** [comment]
I left some comments directly on https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/8ddc3ae8a47ac01c6b8e5cfd07e0da6f39e73bc3 (in case you didn't get notified about it)

File: ADAL/src/request/ADAuthenticationRequest+Broker.m (hunk 1 above)
Comment (RPangrle) [inline ADAL/src/request/ADAuthenticationRequest+Broker.m]: +[ADKeychainUtil retrieveTeamIDFromKeychain] will create the entry it is looking for if it doesn't exist.

And, no, keychainTeamId will not return an empty string and an error either. The error it returns is from retrieveTeamIDFromKeychain when they keychain operation fails. In that case the keychainTeamID never gets set.

**Comment by jasoncoolmax** [comment]
:shipit:

File: ADAL/src/request/ADAuthenticationRequest+Broker.m (hunk 1 above)
Comment (joeydong) [inline ADAL/src/request/ADAuthenticationRequest+Broker.m]: Okay sounds good. I forgot the method was called `retrieveTeamIDFromKeychain` so it doesn't matter if the rest of the app group name isn't the right "adalcache" one.

**Comment by iamshezad** [comment]
"ADKeychainErrorDomain" Code: -34018 ProtocolCode: "(null)" Details: "Keychain failed during "add" operation"
Error: %@ Could not connect to the server.
How to solve this errors???

**Comment by harkmall** [comment]
+1 still getting this error on iOS 11
